config/routes.rb
Codemasters::Application.routes.draw do
  get "skills_users/destroy"

  get "skills/destroy"

  devise_for :users
  resources :users, only: [:index, :show] do
    resources :skills, controller: 'SkillsUsers', only: [:destroy]
  end

  root to: "users#index"
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :description

  has_and_belongs_to_many :users

  def to_s
    description
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :location, :master, :skills

  has_and_belongs_to_many :skills

  validates_presence_of :name, :location
  validates_inclusion_of :master, in: [true, false]

  def title
    master? ? "Master" : "Apprentice"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/skills_users_controller.rb
class SkillsUsersController < ApplicationController
  def destroy
    user = User.find(params[:user_id])
    skill = Skill.find(params[:id])

    user.skills.delete(skill)
    flash[:notice] = "skill #{skill} removed"
    redirect_to user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/skills_users_helper.rb
module SkillsUsersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codemasters</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
    <ul>
      <li><%= link_to "logout", destroy_user_session_path, method: 'delete' %></li>
      <li><%= link_to "profile", user_path(current_user) %></li>
    </ul>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/skills_users/destroy.html.erb
<h1>SkillsUsers#destroy</h1>
<p>Find me in app/views/skills_users/destroy.html.erb</p>

app/views/users/index.html.erb
<h2>Masters</h2>
<table>
    <thead>
        <th>Name</th>
        <th>Location</th>
        <th>Skills</th>
    </thead>
    <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= user.location %></td>
          <td><%= user.skills.map(&:description).join(", ") %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/users/show.html.erb
<div>
    <p><span class="label"><%= @user.title %></span> <%= @user.name %></p>
    <p><span class="label">Location</span> <%= @user.location %></p>
    <p><span class="label">Email</span> <%= @user.email %></p>
    <%= link_to 'Edit', edit_user_registration_path(current_user) %>
</div>

<h2>Skills</h2>
<ul>
    <% @user.skills.each do |skill| %>
    <li><%= skill %> <%= button_to 'remove', user_skill_path(@user, skill), :confirm => "Are you sure?" , :method => :delete %></li>
    <% end %>
</ul>